namespace Tsuki.Framework.Platform.HID;

public enum GenericDesktopUsage : ushort
{
    Pointer = HID.Pointer,
    Mouse = HID.Mouse,
    Joystick = HID.Joystick,
    GamePad = HID.GamePad,
    Keyboard = HID.Keyboard,
    Keypad = HID.Keypad,
    MultiAxisController = HID.MultiAxisController,
    X = HID.X,
    Y = HID.Y,
    Z = HID.Z,
    RotationX = HID.RotationX,
    RotationY = HID.RotationY,
    RotationZ = HID.RotationZ,
    Slider = HID.Slider,
    Dial = HID.Dial,
    Wheel = HID.Wheel,
    Hatswitch = HID.Hatswitch,
    CountedBuffer = HID.CountedBuffer,
    ByteCount = HID.ByteCount,
    MotionWakeup = HID.MotionWakeup,
    Start = HID.Start,
    Select = HID.Select,
    VectorX = HID.VectorX,
    VectorY = HID.VectorY,
    VectorZ = HID.VectorZ,
    VectorXBodyRelative = HID.VectorXBodyRelative,
    VectorYBodyRelative = HID.VectorYBodyRelative,
    VectorZBodyRelative = HID.VectorZBodyRelative,
    VectorNonOriented = HID.VectorNonOriented,
    SystemControl = HID.SystemControl,
    SystemPowerDown = HID.SystemPowerDown,
    SystemSleep = HID.SystemSleep,
    SystemWakeUp = HID.SystemWakeUp,
    SystemContextMenu = HID.SystemContextMenu,
    SystemMainMenu = HID.SystemMainMenu,
    SystemMenuHelp = HID.SystemMenuHelp,
    SystemMenuExit = HID.SystemMenuExit,
    SystemMenuSelect = HID.SystemMenuSelect,
    SystemMenuRight = HID.SystemMenuRight,
    SystemMenuLeft = HID.SystemMenuLeft,
    SystemMenuUp = HID.SystemMenuUp,
    SystemMenuDown = HID.SystemMenuDown,
    DPadUp = HID.DPadUp,
    DPadDown = HID.DPadDown,
    DPadRight = HID.DPadRight,
    DPadLeft = HID.DPadLeft
}