namespace Tsuki.Framework.Platform.HID;

public enum SimulationUsage : ushort
{
    FlightSimulationDevice = HID.FlightSimulationDevice,
    AutomobileSimulationDevice = HID.AutomobileSimulationDevice,
    TankSimulationDevice = HID.TankSimulationDevice,
    SpaceshipSimulationDevice = HID.SpaceshipSimulationDevice,
    SubmarineSimulationDevice = HID.SubmarineSimulationDevice,
    SailingSimulationDevice = HID.SailingSimulationDevice,
    MotorcycleSimulationDevice = HID.MotorcycleSimulationDevice,
    SportsSimulationDevice = HID.SportsSimulationDevice,
    AirplaneSimulationDevice = HID.AirplaneSimulationDevice,
    HelicopterSimulationDevice = HID.HelicopterSimulationDevice,
    MagicCarpetSimulationDevice = HID.MagicCarpetSimulationDevice,
    BicycleSimulationDevice = HID.BicycleSimulationDevice,
    FlightControlStick = HID.FlightControlStick,
    FlightStick = HID.FlightStick,
    CyclicControl = HID.CyclicControl,
    CyclicTrim = HID.CyclicTrim,
    FlightYoke = HID.FlightYoke,
    TrackControl = HID.TrackControl,
    AileronControl = HID.AileronControl,
    AileronTrim = HID.AileronTrim,
    AntiTorqueControl = HID.AntiTorqueControl,
    AutopilotEnable = HID.AutopilotEnable,
    ChaffRelease = HID.ChaffRelease,
    CollectiveControl = HID.CollectiveControl,
    DiveBrake = HID.DiveBrake,
    ElectronicCountermeasures = HID.ElectronicCountermeasures,
    ElevatorControl = HID.ElevatorControl,
    ElevatorTrim = HID.ElevatorTrim,
    Rudder = HID.Rudder,
    Throttle = HID.Throttle,
    FlightCommunications = HID.FlightCommunications,
    FlareRelease = HID.FlareRelease,
    LandingGear = HID.LandingGear,
    ToeBrake = HID.ToeBrake,
    Trigger = HID.Trigger,
    WeaponsArm = HID.WeaponsArm,
    WeaponsSelect = HID.WeaponsSelect,
    WindFlaps = HID.WindFlaps,
    Accelerator = HID.Accelerator,
    Brake = HID.Brake,
    Clutch = HID.Clutch,
    Shifter = HID.Shifter,
    Steering = HID.Steering,
    TurretDirection = HID.TurretDirection,
    BarrelElevation = HID.BarrelElevation,
    DivePlane = HID.DivePlane,
    Ballast = HID.Ballast,
    BicycleCrank = HID.BicycleCrank,
    HandleBars = HID.HandleBars,
    FrontBrake = HID.FrontBrake,
    RearBrake = HID.RearBrake
}